# Generated by Django 4.2.7 on 2024-01-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_alter_mobile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='img',
            field=models.ImageField(default=' ', upload_to='images'),
        ),
    ]
